name: ecommerce_app
description: Flutter eCommerce app (part of the Complete Flutter Course Bundle)

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: 1.0.4
  flutter_localizations:
    sdk: flutter
  intl: 0.17.0 # Used for date and currency formatting
  flutter_layout_grid: 1.0.3 # Used for content-sized items in the products grid layout
  flutter_rating_bar: 4.0.0 # Used for the "leave a rating" feature

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/products/
